### PR TITLE
attempt travis-ci fix for mapnik

### PR DESCRIPTION
**Pull request by ungoldman**
> https://github.com/mapnik/node-mapnik#troubleshooting

Got mapnik install working for travis-ci test.

Failing test (utf-tiles) fails locally as well (cc @chelm).

### CODE REVIEW

**Comment by chelm** [comment]
Neat. Will look at it

**Comment by chelm** [comment]
@ngoldman :wrench:

**Comment by ungoldman** [comment]
@chelm what changed?

**Comment by chelm** [comment]
@ngoldman a change in the way the utf tile wanted to be encoded. https://github.com/chelm/mapnik-tiles/commit/92ed2ee8220374a26e2a2b80627a3ef55585e8a1

**Comment by ungoldman** [comment]
Dope.

**Pull request merged**
